{
 "title": "dmn-drools-quarkus-metrics_9.2.0-ibm-0004 - LoanEligibility - Operational Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "LoanEligibility endpoint request count per day",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code_total{endpoint=\"LoanEligibility\", artifactId=\"dmn-drools-quarkus-metrics\", version=\"9.2.0-ibm-0004\"}[1d]))"
    }
   ]
  },
  {
   "title": "Average requests per minute to LoanEligibility endpoint",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code_total{endpoint=\"LoanEligibility\", artifactId=\"dmn-drools-quarkus-metrics\", version=\"9.2.0-ibm-0004\"}[1m]))"
    }
   ]
  },
  {
   "title": "Execution time quantiles for endpoint LoanEligibility",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_execution_elapsed_seconds_sum{endpoint=\"LoanEligibility\", artifactId=\"dmn-drools-quarkus-metrics\", version=\"9.2.0-ibm-0004\"}[1m]))/sum(increase(api_execution_elapsed_seconds_count{endpoint=\"LoanEligibility\", artifactId=\"dmn-drools-quarkus-metrics\", version=\"9.2.0-ibm-0004\"}[1m]))"
    }
   ]
  },
  {
   "title": "LoanEligibility endpoint status code responses per minute",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (identifier) (increase(api_http_response_code_total{endpoint=\"LoanEligibility\", artifactId=\"dmn-drools-quarkus-metrics\", version=\"9.2.0-ibm-0004\"}[1m]))"
    }
   ]
  },
  {
   "title": "Exceptions details",
   "type": "table",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (identifier) (increase(api_http_stacktrace_exceptions_total{endpoint=\"LoanEligibility\", artifactId=\"dmn-drools-quarkus-metrics\", version=\"9.2.0-ibm-0004\"}[1d]))"
    }
   ]
  },
  {
   "title": "Exception count per day",
   "type": "stat",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_stacktrace_exceptions_total{endpoint=\"LoanEligibility\", artifactId=\"dmn-drools-quarkus-metrics\", version=\"9.2.0-ibm-0004\"}[1d]))"
    }
   ]
  }
 ]
}